rn5f107s2/Molybdenum

src/search.cpp
Elo   | 0.76 +- 4.95 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=8MB
LLR   | 0.10 (-2.25, 2.89) [-4.00, 6.00]
Games | N: 10920 W: 3165 L: 3141 D: 4614
Penta | [319, 1294, 2192, 1354, 301]
Passes [-10.00, 0.00]
ELO: 0.764 +- 4.95 [-4.18, 5.71]
LLR: 6.27 [-10.0, 0.0] (-2.94, 2.94)
H1 Accepted
This was tested with non-regr bounds because the default depth reduction is something I fell like is useful for the future, after this commit a tune will follow after which simplyfing this back will be tried
bench 7202758
=> Reduce the depth by one by default

.gitignore, CMakeLists.txt, Makefile, src/MagicBitboards.h, src/Movegen.h, src/incbin/incbin.h, src/nnue.cpp, src/nnue.h
The undef MSC_VER hack as well as the updatet incbin.h file are taken from Stormphrax, the other stuff was mostly fixing bad code that somehow compiled on linux 
bench 6015111
=> Fix compiling errors on windows

src/Movepicker.h, src/search.cpp
Elo   | 6.88 +- 5.26 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8030 W: 2008 L: 1849 D: 4173
Penta | [126, 896, 1843, 993, 157]
http://aytchell.eu.pythonanywhere.com/test/90/
bench 7499086
=> If a move failed singular search high, sort it right after the ttMove

src/search.cpp, src/searchUtil.h
Elo   | 18.25 +- 9.26 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2648 W: 718 L: 579 D: 1351
Penta | [31, 300, 553, 379, 61]
http://aytchell.eu.pythonanywhere.com/test/97/
bench 7287389
=> Probe the TT in qsearch and cut-off arcodingly

src/search.cpp
Elo   | 16.94 +- 8.66 (95%)
LLR   | 3.10 (-2.25, 2.89) [0.00, 5.00]
Games | N: 3058 W: 831 L: 682 D: 1545
Penta | [44, 323, 678, 408, 76]
http://aytchell.eu.pythonanywhere.com/test/100/
bench 6594679
=> If the ttMove is a cpature use it for ordering in qs

src/timemanagment.cpp
Passed STC:
Elo   | 10.88 +- 7.07 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 4536 W: 1181 L: 1039 D: 2316
Penta | [53, 523, 1006, 601, 85]
http://aytchell.eu.pythonanywhere.com/test/135/
Passed LTC:
Elo   | 9.85 +- 6.81 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 4514 W: 1085 L: 957 D: 2472
Penta | [32, 475, 1124, 585, 41]
http://aytchell.eu.pythonanywhere.com/test/136/
bench 7526987
=> Tune timemanagment at 20+0.2 for 1.5k Iterations

src/search.cpp, src/search.h
In history pruning deduct fractional reductions with one fourth precision from the total margin
Passed STC:
Elo   | 8.90 +- 6.27 (95%)
Games | N: 5738 W: 1472 L: 1325 D: 2941
Penta | [65, 679, 1282, 730, 113]
http://aytchell.eu.pythonanywhere.com/test/143/
bench 6606439
=> Deduct fractional depths from history pruning margin

src/search.cpp, src/search.h
Passed STC:
Elo   | 6.26 +- 5.09 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8604 W: 2152 L: 1997 D: 4455
Penta | [101, 986, 1983, 1121, 111]
http://aytchell.eu.pythonanywhere.com/test/152/
bench 5751949
=> Subtract quarter reductions of previous ply from mcp depth

src/search.cpp
Passed STC:
Elo   | 3.47 +- 3.22 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 21510 W: 5288 L: 5073 D: 11149
Penta | [322, 2518, 4867, 2719, 329]
http://aytchell.eu.pythonanywhere.com/test/159/
bench explosion seems to be caused by one specific position, where search jumps to 10m nodes at d13
bench 19148590
=> Also apply fractional depth to fp

src/search.cpp, src/search.h, src/searchUtil.h
Elo   | 9.38 +- 6.51 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
Games | N: 4742 W: 1092 L: 964 D: 2686
Penta | [29, 511, 1176, 613, 42]
http://aytchell.eu.pythonanywhere.com/test/203/
bench 9911652
=> Tuned at 1200 Iterations 40+0.4, excludung some parametetrs

src/search.cpp
If we hit a higher depth entry that suggests the current bestScore is inaccurate, set it to ttScore
Elo   | 4.20 +- 3.77 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 15640 W: 3856 L: 3667 D: 8117
Penta | [216, 1816, 3615, 1909, 264]
http://aytchell.eu.pythonanywhere.com/test/222/
bench 7290550
=> Adjust returned score based on ttScore

src/search.cpp, src/search.h
idea being that trees resulting from later root moves are less likely to produce a good line therfore are less valuable to extend
Passed STC:
Elo   | 3.71 +- 3.42 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 5.00]
Games | N: 19178 W: 4759 L: 4554 D: 9865
Penta | [259, 2302, 4285, 2461, 282]
http://aytchell.eu.pythonanywhere.com/test/231/
Passed MTC:
Elo   | 13.54 +- 8.33 (95%)
SPRT  | 20.0+0.20s Threads=1 Hash=16MB
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 3158 W: 809 L: 686 D: 1663
Penta | [15, 337, 767, 430, 30]
http://aytchell.eu.pythonanywhere.com/test/241/
Passed LTC:
Elo   | 14.79 +- 8.37 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2986 W: 738 L: 611 D: 1637
Penta | [21, 318, 705, 411, 38] …
=> Adjust Se margin based on root movecount

src/search.cpp
Elo   | 6.25 +- 5.00 (95%)
Games | N: 8842 W: 2192 L: 2033 D: 4617
Penta | [124, 1017, 1982, 1172, 126]
http://aytchell.eu.pythonanywhere.com/test/244/
bench 6732456
=> MCP more when not improving

src/Movepicker.h, src/search.cpp
Allow captures as killers, update them on beating alpha not beta and search them before captures
Passed STC:
Elo   | 4.21 +- 3.87 (95%)
Games | N: 14594 W: 3529 L: 3352 D: 7713
Penta | [155, 1700, 3442, 1813, 187]
http://aytchell.eu.pythonanywhere.com/test/388/
bench 6257966
=> Update killers in a different way at root

src/search.cpp
Passed VSTC:
Elo   | 3.34 +- 3.08 (95%)
SPRT  | 2.0+0.02s Threads=1 Hash=4MB
LLR   | 2.98 (-2.25, 2.89) [0.00, 5.00]
Games | N: 25616 W: 6869 L: 6623 D: 12124
Penta | [498, 2922, 5750, 3112, 526]
http://aytchell.eu.pythonanywhere.com/test/399/
bench 4881740
=> Prefetch the TTEntry after a nullmove

src/search.cpp
Before this, if a move scored above beta from the reduced search, the node would fail high without researching the move at full depth
Passed STC:
Elo   | 6.11 +- 5.04 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8816 W: 2208 L: 2053 D: 4555
Penta | [94, 1038, 2009, 1153, 114]
http://aytchell.eu.pythonanywhere.com/test/400/
bench 4870687
=> Research PVNode LMR fail highs with full depth but zero window first

src/nnue.cpp
The output bias is qunatized using QA * QB, so / (QA * QA * QB) is only applicalble to the output of the hidden layer and not the output neuron (SCReLU)
Passed STC:
Elo   | 9.43 +- 7.58 (95%)
LLR   | 2.92 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 3868 W: 981 L: 876 D: 2011
Penta | [48, 435, 881, 504, 66]
http://aytchell.eu.pythonanywhere.com/test/425/
bench 4940522
=> Fix quantization of output bias

src/search.cpp
Static eval is not needed this early, therfore not evaluating when a cutoff happens saves an evaluate call
Passed VSTC:
Elo   | 6.72 +- 5.34 (95%)
SPRT  | 2.0+0.02s Threads=1 Hash=4MB
Games | N: 8434 W: 2276 L: 2113 D: 4045
Penta | [152, 925, 1922, 1044, 174]
http://aytchell.eu.pythonanywhere.com/test/427/
bench 4940522
=> Dont evaluate before ttCutoffs

src/eval.h, src/nnue.cpp
Passed Non regr 25k fixed nodes
Elo   | 1.39 +- 4.04 (95%)
SPRT  | N=25000 Threads=1 Hash=8MB
LLR   | 3.06 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 16486 W: 4827 L: 4761 D: 6898
Penta | [526, 1940, 3248, 2000, 529]
http://aytchell.eu.pythonanywhere.com/test/457/
bench 4546084
=> Move eval divisor to where eval scale is applied

src/search.cpp
This inspired by a message by https://github.com/tsoj talking about having a nightmare, were he thought he woke up, however it turned out he didnt. The nightmare in this this patch is the three first moves scoring well below alpha, we expect these moves to be the best, so if those all score badly, we dont necessarily expect to have a later move beat alpha an therefore induce a research. So if we do "wake up" by finding a move that does beat alpha, we check carefully that we did indeed wake up by extending the search, in order to avoid thinking we woke up and therfore return a fail high/ take this as a alpha beating score, if we did not wake up. Something to note is that this patch is similar to the doDepper idea, infact, a nightmare would almost always imply a doDeeper, however a doDeeper …
=> Extend research if all prior moves were bad

src/UCI.cpp, src/UCI.h, src/main.cpp, src/search.cpp, src/search.h, src/timemanagement.h, src/timemanagment.cpp
Shouldnt be functional, temporarily breaks datagen,
no crashes / anything else at 2+0.02
Elo   | -0.26 +- 4.24 (95%)
SPRT  | 2.0+0.02s Threads=1 Hash=4MB
LLR   | 1.13 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 13212 W: 3381 L: 3391 D: 6440
Penta | [241, 1549, 3038, 1535, 243]
http://aytchell.eu.pythonanywhere.com/test/479/
No non drawn pairs at 25k nodes
Elo   | -0.00 +- 13.65 (95%)
SPRT  | N=25000 Threads=1 Hash=8MB
LLR   | 0.29 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 1406 W: 398 L: 398 D: 610
Penta | [0, 0, 703, 0, 0]
http://aytchell.eu.pythonanywhere.com/test/480/
bench 5022919
=> Refactor UCI handling

src/UCI.cpp, src/UCI.h, src/UCIOptions.cpp, src/UCIOptions.h, src/search.cpp, src/search.h, src/thread.cpp, src/thread.h
Passed 2v1 thread STC:
Elo   | 82.15 +- 19.43 (95%)
SPRT  | 8.0+0.08s Threads=2 Hash=8MB
Games | N: 616 W: 223 L: 80 D: 313
Penta | [1, 38, 111, 133, 25]
http://aytchell.eu.pythonanywhere.com/test/485/
Non non drawn game pairs on 25k fixed nodes:
Elo   | -0.00 +- 10.04 (95%)
Conf  | N=25000 Threads=1 Hash=8MB
Games | N: 2564 W: 716 L: 716 D: 1132
Penta | [0, 0, 1282, 0, 0]
http://aytchell.eu.pythonanywhere.com/test/488/
Passed Non regr 1v1 thread STC:
Elo   | 13.06 +- 9.20 (95%)
LLR   | 2.90 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 2662 W: 697 L: 597 D: 1368
Penta | [19, 258, 694, 324, 36]
http://aytchell.eu.pythonanywhere.com/test/484/
The good result is probably caused by a speedup, not sure where it comes from …
=> Implement lazySMP

.github/workflows/build.yaml
Upload Windows artifact (Molybdenum-$hash.exe) so it can be downloaded
=> Github workflow will store the windows exe

src/searchUtil.h
If the stage is King and incremented by one, the stage would overflow leading to reading from bitboards that, in this context, are nonsensical
Passed Non-Regr:
Elo   | 29.49 +- 12.84 (95%)
LLR   | 2.91 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 1358 W: 384 L: 269 D: 705
Penta | [8, 136, 293, 217, 25]
https://aytchell.eu.pythonanywhere.com/test/710/
bench 7874387
=> Fix an overflow in SEE

src/search.cpp, src/search.h
Semi non regr because I need this for some wdl output ideas
Elo   | 1.93 +- 3.23 (95%)
LLR   | 2.90 (-2.25, 2.89) [-2.50, 2.50]
Games | N: 20004 W: 4579 L: 4468 D: 10957
Penta | [152, 2350, 4917, 2401, 182]
https://aytchell.eu.pythonanywhere.com/test/711/
bench 8493466
=> Dont allow tt cuts in qs pv

src/search.cpp, src/search.h
Non regr VSTC:
Elo   | 0.50 +- 3.34 (95%)
SPRT  | 2.0+0.02s Threads=1 Hash=4MB
LLR   | 2.91 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 20828 W: 5248 L: 5218 D: 10362
Penta | [262, 2315, 5261, 2283, 293]
https://aytchell.eu.pythonanywhere.com/test/713/
bench 8493466
=> Display wdl calculate with a WDL head during search
